#pragma once

// PERSONAL CONFIG
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 200

// SPLIT CONFIGURATION
#define MASTER_LEFT
// #define MASTER_RIGHT
// #define EE_HANDS

// SPLIT CONFIGURATION?
//#define USE_MATRIX_I2C
#define USE_SERIAL_PD2

// OLED CONFIGURATION
#define SSD1306OLED

