#pragma once

/* SPLIT */
#define EE_HANDS

/* OLED */
#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"

/* RGB */
#ifdef RGB_MATRIX_ENABLE
#	define RGB_DISABLE_WHEN_USB_SUSPENDED true
#	define RGB_DISABLE_TIMEOUT 60000
#	define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120 // Crashes otherwise
#	define RGB_MATRIX_HUE_STEP 4
#	define RGB_MATRIX_SAT_STEP 4
#	define RGB_MATRIX_VAL_STEP 4
#	define RGB_MATRIX_SPD_STEP 10

#	define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#	define RGB_MATRIX_KEYPRESSES

//#	define DISABLE_RGB_MATRIX_SOLID_COLOR
#	define DISABLE_RGB_MATRIX_ALPHAS_MODS
#	define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#	define DISABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
//#	define DISABLE_RGB_MATRIX_BREATHING
#	define DISABLE_RGB_MATRIX_BAND_SAT
#	define DISABLE_RGB_MATRIX_BAND_VAL
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
//#	define DISABLE_RGB_MATRIX_CYCLE_ALL
#	define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#	define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#	define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
//#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#	define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#	define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#	define DISABLE_RGB_MATRIX_DUAL_BEACON
#	define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#	define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#	define DISABLE_RGB_MATRIX_RAINDROPS
#	define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
//#	define DISABLE_RGB_MATRIX_TYPING_HEATMAP
#	define DISABLE_RGB_MATRIX_DIGITAL_RAIN
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#	define DISABLE_RGB_MATRIX_SPLASH
#	define DISABLE_RGB_MATRIX_MULTISPLASH
#	define DISABLE_RGB_MATRIX_SOLID_SPLASH
//#	define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH

#endif

/* BASE LAYOUT */
#define \
	NJD_BASE_LAYOUT( \
		NJD_KM_Q, NJD_KM_W, NJD_KM_E, NJD_KM_R, NJD_KM_T, NJD_KM_Y, NJD_KM_U, NJD_KM_I    , NJD_KM_O  , NJD_KM_P     , \
		NJD_KM_A, NJD_KM_S, NJD_KM_D, NJD_KM_F, NJD_KM_G, NJD_KM_H, NJD_KM_J, NJD_KM_K    , NJD_KM_L  , NJD_KM_SCOLON, \
		NJD_KM_Z, NJD_KM_X, NJD_KM_C, NJD_KM_V, NJD_KM_B, NJD_KM_N, NJD_KM_M, NJD_KM_COMMA, NJD_KM_DOT, NJD_KM_SLASH , \
		NJD_KM_LMAMOD, NJD_KM_BSPACE  , \
		NJD_KM_LMIMOD, NJD_KM_RMAMOD  , \
		NJD_KM_LSHIFT, NJD_KM_RSHIFT  , \
		NJD_KM_SPACE , NJD_KM_ENTER   , \
		NJD_KM_LOWER , NJD_KM_RAISE   , \
		NJD_KM_LALT  , NJD_KM_FUNCTION  \
	) \
	LAYOUT( \
		NJD_KM_LMAMOD, NJD_KM_Q, NJD_KM_W, NJD_KM_E, NJD_KM_R, NJD_KM_T,      NJD_KM_Y, NJD_KM_U, NJD_KM_I    , NJD_KM_O  , NJD_KM_P     , NJD_KM_BSPACE, \
		NJD_KM_LMIMOD, NJD_KM_A, NJD_KM_S, NJD_KM_D, NJD_KM_F, NJD_KM_G,      NJD_KM_H, NJD_KM_J, NJD_KM_K    , NJD_KM_L  , NJD_KM_SCOLON, NJD_KM_RMAMOD, \
		NJD_KM_LSHIFT, NJD_KM_Z, NJD_KM_X, NJD_KM_C, NJD_KM_V, NJD_KM_B,      NJD_KM_N, NJD_KM_M, NJD_KM_COMMA, NJD_KM_DOT, NJD_KM_SLASH , NJD_KM_RSHIFT, \
		                        NJD_KM_LALT, NJD_KM_LOWER, NJD_KM_SPACE,      NJD_KM_ENTER, NJD_KM_RAISE, NJD_KM_FUNCTION \
	)

