#pragma once

#define FORCE_NKRO
#define ONESHOT_TAP_TOGGLE 0
#define TAPPING_TERM 200
//#define TAPPING_FORCE_HOLD

#ifdef AUDIO_ENABLE
#	define DEFAULT_LAYER_SONGS { \
		SONG(QWERTY_SOUND ), \
		SONG(DVORAK_SOUND ), \
		SONG(COLEMAK_SOUND), \
		SONG(COLEMAK_SOUND), \
		SONG(COLEMAK_SOUND), \
		SONG(WORKMAN_SOUND)  \
	}
#endif
